import type { Metadata } from "next";
import { Noto_Sans_Lao_Looped } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"

import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairEffect";
import Footer from "@/components/Footer";
const notoSansLaoLooped = Noto_Sans_Lao_Looped({ 
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"], 
    variable: '--font-notoSansLaoLooped'
    });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return ( 
    <html lang="en">
      <body className={notoSansLaoLooped.variable}>
      
        <Header />
        {/* <StairTransition /> */}

        {/* <PageTransition> */}

        {children}
        {/* </PageTransition> */}
        {/* <Footer /> */}
        </body>
    </html>
  );
}
